spring:
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 1800000
# Добавить настройки вашей локальной бд
  datasource:
    url:
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
# Добавить настройки вашего локального фронта пример: http://localhost:3080
  cors:
    allowed:
      origins:
# Локальнрое приложение бужет работать на url http://localhost:8080/local
server:
  port: 8080
  servlet:
    context-path: /local