spring:
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 1800000

  datasource:
    url: jdbc:mysql://91.211.249.37:32500/wt_backend_test
    username: backend_test
    password: d2343&^2dsjsds

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cors:
    allowed:
      origins: http://91.211.249.37:30080
      local: http://localhost:3000

server:
  port: 8080
  servlet:
    context-path: /test