name: Deploy to K3s

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Сборка JAR файла
        run: ./gradlew build -x test

      - name: Копирование файла на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/WorkTask-0.0.1-SNAPSHOT.jar"
          target: "/home/deployer/backend"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Подключение по SSH и деплой в K3s
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/backend
            docker build -t backend:latest .
            docker save -o backend.tar backend:latest
            scp backend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/backend
            ctr -n k8s.io images import /home/${{ secrets.SERVER_USER }}/backend.tar
            k3s kubectl delete deployment myapp || true
            k3s kubectl apply -f deployment.yaml